# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jogai < Formula
  desc "AI session recaps — jog your memory"
  homepage "https://github.com/Cassidy321/jogai"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Cassidy321/jogai/releases/download/v0.2.1/jogai_0.2.1_darwin_amd64.tar.gz"
      sha256 "660c570739c9a64670bf762e5685d2af063d9de9577c541435db0706ea1d7672"

      define_method(:install) do
        bin.install "jogai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Cassidy321/jogai/releases/download/v0.2.1/jogai_0.2.1_darwin_arm64.tar.gz"
      sha256 "64b18d6c69d2a6bcf61fe8423bacce97c180aa10ce7b0b024085c485aa24a3fa"

      define_method(:install) do
        bin.install "jogai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cassidy321/jogai/releases/download/v0.2.1/jogai_0.2.1_linux_amd64.tar.gz"
      sha256 "fc6621419aa09a7dcca1070b36ce6900231a5d016c5adffa709422525ae5ac2e"
      define_method(:install) do
        bin.install "jogai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cassidy321/jogai/releases/download/v0.2.1/jogai_0.2.1_linux_arm64.tar.gz"
      sha256 "497d2899c1c8284b29b79dfe4243b9a203fe0ec5187c565a543962e714f416f9"
      define_method(:install) do
        bin.install "jogai"
      end
    end
  end
end
