# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jogai < Formula
  desc "AI session recaps — jog your memory"
  homepage "https://github.com/Cassidy321/jogai"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Cassidy321/jogai/releases/download/v0.2.0/jogai_0.2.0_darwin_amd64.tar.gz"
      sha256 "caa264716e0ad5d45b6fa4a66bb4362ea19b8afbf6a85eebd789e600b6bf8e66"

      define_method(:install) do
        bin.install "jogai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Cassidy321/jogai/releases/download/v0.2.0/jogai_0.2.0_darwin_arm64.tar.gz"
      sha256 "fa086ac7038930a3f7bf20c5f4eef370341e4d6e270f4cc874097a554cc1eaa8"

      define_method(:install) do
        bin.install "jogai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cassidy321/jogai/releases/download/v0.2.0/jogai_0.2.0_linux_amd64.tar.gz"
      sha256 "c9c683d1596913ba32f501747c23a5b9dc0001d60ccb6772afec13aff0272dec"
      define_method(:install) do
        bin.install "jogai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cassidy321/jogai/releases/download/v0.2.0/jogai_0.2.0_linux_arm64.tar.gz"
      sha256 "3c51ac3471d5c941787aa146a8a39ae090a619d83beecf45ab69c8b22e476025"
      define_method(:install) do
        bin.install "jogai"
      end
    end
  end
end
